import "@styles/app.scss";

const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = (props) => {
	const { children } = props;

	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export { metadata };
export default RootLayout;
